In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import regularizers
import matplotlib.pyplot as plt
from math import ceil, log, exp
from sklearn import preprocessing
from mpl_toolkits import mplot3d
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping
from keras.callbacks import EarlyStopping
from sklearn.cluster import KMeans
import matplotlib.colors as mcolors


tf.keras.utils.set_random_seed(seed=100)

## AutoEncoder 

In [4]:
class AutoEncoder(tf.keras.Model):
    def __init__(self, x_train):
        super().__init__()
        self.encoder = self.encoder_model()
        self.decoder = self.decoder_model()
        self.total_loss_tracker = keras.metrics.Mean(name="total_loss")
        self.reconstruction_loss_tracker = keras.metrics.Mean(name="reconstruction_loss")
        self.train_data = x_train
        

    def encoder_model(self):
        encoder_inputs = keras.Input(shape=(6,)) # the shape is the number of dimensions and the length of data that will be put in. 
        # i.e. 6dims and 1 data points
        
        

        encoded = layers.Dense(5, activation='tanh')(encoder_inputs)
        encoded = layers.Dense(4, activation='tanh')(encoded)
        latent_space = layers.Dense(3, activation='tanh')(encoded) # this is the latent space (the output of the encoder)
        
        encoder = keras.Model(encoder_inputs, latent_space) # this defines the model in the keras computational graph
        encoder.compile(optimizer='Adam', loss='mse') # the compile step of the keras model
        encoder.summary()
        return encoder # returns the compiled model
    
    def decoder_model(self):
        decoder_inputs = keras.Input(shape=(3,)) # these are the inputs of the decoder (3dims (the latent space), 1 number of data points)
        decoded = layers.Dense(4, activation='tanh')(decoder_inputs)
        decoded = layers.Dense(5, activation='tanh')(decoded)     
        output_space = layers.Dense(6, activation='sigmoid')(decoded) # the output (decoded latent space, should be the inputs)
        
        decoder = keras.Model(decoder_inputs, output_space) # defining the decoder as a Model
        decoder.compile(optimizer='Adam', loss='mse') # compiling the model
        decoder.summary()
        return decoder # returning the compiled model
    
    
    
    def train_step(self, data): # as we have two parts of the model, we have to define how the model should be trained to access the latent space
        with tf.GradientTape() as tape:
            latent_output = self.encoder(data)
            reconstructed_data = self.decoder(latent_output)
            reconstruction_loss = tf.reduce_mean(tf.reduce_sum(keras.losses.mean_squared_logarithmic_error(data, reconstructed_data)))
            total_loss = reconstruction_loss
            
        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))
        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        return {'total_loss': self.total_loss_tracker.result(),
                'reconstruction_loss': self.reconstruction_loss_tracker.result()}

## Preprocessing Functions

In [5]:
class preprocessing:

    def map_unique_values(self, arr): #function to enforce even spacing in categorical data
        unique_values = list(set(arr))
        unique_values.sort() 
        value_to_number_mapping = {value: i + 1 for i, value in enumerate(unique_values)}
        mapped_array = np.array([value_to_number_mapping[value] for value in arr])
        return mapped_array
    
    def map_unique_values_to_columns(self, np_array):
        mapped_columns = []
        for col_idx in range(np_array.shape[1]):
            mapped_column = self.map_unique_values(np_array[:, col_idx])
            mapped_columns.append(mapped_column)
        return np.array(mapped_columns).T

    

    def order_by_frequency_array(self, data): #function used to value each data point based on freq
        value_counts = {}
        for value in data:
            if value in value_counts:
                value_counts[value] += 1
            else:
                value_counts[value] = 1
                
        sorted_values = sorted(value_counts.keys(), key=lambda x: value_counts[x], reverse=False)
        rank_mapping = {value: rank for rank, value in enumerate(sorted_values, start=1)}
        ranked_data = [rank_mapping[value] for value in data]
    
        return ranked_data


    def order_by_frequency(self, array): #function used to carry out valueing over each column
        output = []
        for column in array.T:
            ranked_data = self.order_by_frequency_array(column)
            output.append(ranked_data)
        output_array = np.column_stack(output)
    
        return output_array

    
    
    def min_max(array):
        min_val = np.min(array, axis=0)
        max_val = np.max(array, axis=0)
        normalized_array = (array - min_val) / (max_val - min_val)
        return normalized_array


    def min_max_odd_columns(array):
        normalized_array = np.empty_like(array)
        for i in range(array.shape[1]):
            if i % 2 != 0:
                normalized_array[:, i] = array[:, i]
            else: 
                min_val = np.min(array[:, i])
                max_val = np.max(array[:, i])
                normalized_array[:, i] = (array[:, i] - min_val) / (max_val - min_val)
        return normalized_array


## K-means Clustering

In [7]:
class clustering:

    def assign_clusters_find_distances(self, new_data, centroids):
            # calculate distances to centroids
            distances = np.linalg.norm(new_data[:, np.newaxis] - centroids, axis=2)
            
            # Assign each point to the closest centroid
            cluster_assignment = np.argmin(distances, axis=1)
            
            # Get distances to the closest centroid
            min_distances = np.min(distances, axis=1)
            
            return cluster_assignment, min_distances


    def kmean_clustering_with_distances(self, data, num_clusters):
        num_columns = data.shape[1]
        centroids_list = []
        assignment_distances_list = []
        
        # Iterate over each column
        for i in range(num_columns):
            # remove i-th column from the data
            data_subset = np.delete(data, i, axis=1)
            
            #K-means clustering
            kmeans = kmeans = KMeans(n_clusters=num_clusters, random_state=0, n_init=10).fit(data_subset)
            
            # record cluster centroids
            centroids = kmeans.cluster_centers_
            centroids_list.append(centroids)
            
            # get clusters and distances
            cluster_assignment, distances = self.assign_clusters_find_distances(data_subset, centroids)
            assignment_distances_list.append(cluster_assignment)
            assignment_distances_list.append(distances)
        
        # stack centroids into a single array
        stacked_centroids = np.stack(centroids_list, axis=1)
    
        # stack assignments and distances into a single array
        stacked_assignment_distances = np.column_stack(assignment_distances_list)
        
        return stacked_centroids, stacked_assignment_distances




    

    def kmeans_clustering_with_distances_new_data(self, stacked_centroids, data): 
            num_columns = stacked_centroids.shape[1]
            assignment_distances_list = []
            
            # Iterate over each column
            for i in range(num_columns):
                # Get the centroids for the current iteration
                centroids = stacked_centroids[:, i, :]
                
                # Remove the i-th column from the data
                data_subset = np.delete(data, i, axis=1)
                
                # Assign clusters and distances using the provided centroids
                cluster_assignment, distances = self.assign_clusters_find_distances(data_subset, centroids)
                assignment_distances_list.append(cluster_assignment)
                assignment_distances_list.append(distances)
            
            # Stack assignments and distances into a single array
            assignment_distances = np.column_stack(assignment_distances_list)
            
            return assignment_distances

## Data Analysis Functions

In [8]:
class data_analysis:

    def calculate_gradient(self, x, y):
        if len(x) != len(y):
            raise ValueError("Arrays must be of the same length")
        
        # Perform linear regression to find the slope (gradient)
        m, _ = np.polyfit(x, y, 1)
        
        return m

    def calculate_average_grad(self, data_set1, data_set2):
        gradients = []
        for i in range(data_set1.shape[1]):
            gradient = self.calculate_gradient(data_set1[:, i], data_set2[:, i])
            gradients.append(gradient)
        
        gradients = np.array(gradients)
        average_gradient = np.mean(gradients)
        
        return gradients, average_gradient


    def calculate_r_square(self, array1, array2):
            if array1.shape[1] != array2.shape[1]:
                raise ValueError("Arrays must have the same number of columns")
            
            r_squared_values = []
            for i in range(array1.shape[1]):
                correlation_matrix = np.corrcoef(array1[:, i], array2[:, i])
                correlation_coefficient = correlation_matrix[0, 1]
                r_squared = correlation_coefficient ** 2
                r_squared_values.append(r_squared)
        
            r_squared_values = np.array(r_squared_values)
            average_r_squared = np.mean(r_squared_values)
            
            return r_squared_values, average_r_squared
    
    def plot_hexbin_log_frequency(x, y, xlabel="", ylabel="", title="", gridsize=100, cmap='viridis', colorbar=True):
        """
        Function to create a hexbin plot with log-scaled frequency using Matplotlib.
        """
        plt.figure(figsize=(8, 6))
        
        # Calculate the hexbin frequencies
        hb = plt.hexbin(x, y, gridsize=gridsize, cmap=cmap)
        counts = hb.get_array()
        nonzero_counts = counts[counts != 0]
        
        # Set the norm to LogNorm with vmin=0
        norm = mcolors.LogNorm(vmin=1, vmax=nonzero_counts.max())
        hb = plt.hexbin(x, y, gridsize=gridsize, cmap=cmap, norm=norm)
        
        plt.xlabel(xlabel)
        plt.ylabel(ylabel)
        plt.title(title)
        
        if colorbar:
            plt.colorbar(hb, label='log(count)')
        
        plt.show()

In [9]:
x_data_raw = np.loadtxt('train4 .csv',delimiter = ',') #import training data as numpy array

In [10]:
#seperate categorical and continuous
categorical_data = np.delete(x_data_raw, 5, axis=1)
x6 = x_data_raw[:, 5]

In [11]:
#create instances for classes
preprocessor = preprocessing()
Cluster = clustering()
Analyse = data_analysis()

In [12]:
#Preprocess Categorical Data

#apply even spacing

mapped = preprocessor.map_unique_values_to_columns(categorical_data)

#order

ordered = preprocessor.order_by_frequency(mapped)


#normalise 
ordered_min_max = preprocessing.min_max(ordered)

print(ordered_min_max)

[[0.72889694 1.         0.98461538 0.98848624 0.97415385]
 [0.01786639 1.         1.         0.883091   0.88      ]
 [0.17115484 1.         0.96923077 0.99785962 0.99938462]
 ...
 [0.88114966 1.         0.93846154 0.75798952 0.79630769]
 [0.17400311 1.         0.93846154 0.87881024 0.99938462]
 [0.42180218 1.         0.96923077 0.9988191  0.99815385]]


In [13]:
#Preprocess Continuous Data

log_x6 = np.log10(x6)
x6_logged_normalized = preprocessing.min_max(log_x6)

In [14]:
Input_data = np.column_stack((ordered_min_max, x6_logged_normalized))

In [16]:
x_train = Input_data
#x_test = Input_data[ceil(0.8*len(Input_data)):] change this to validation

In [ ]:
#Train AutoEncoder #after changing all test stuff, check that auto encoder still runs without test bit

AutoEncoder = AutoEncoder(x_train)
AutoEncoder.compile(optimizer=keras.optimizers.Adam())
AutoEncoder.fit(x_train, epochs= 2000 , batch_size=200)

In [ ]:
#Run with Trianing Data

latent_space_representation = AutoEncoder.encoder.predict(Input_data)

Output_data = AutoEncoder.decoder.predict(latent_space_representation)

In [ ]:
#Find Reconstruction Loss
Reconstruction_loss = np.mean(np.square(x_train - Output_data), axis = 1)
Threshold = np.percentile(Reconstruction_loss, 99.0)
print(Threshold)

In [ ]:
#Find Gradients
all_gradients, average_gradient = Analyse.calculate_average_grad(Input_data, Output_data)
print(average_gradient)

In [ ]:
#Find r^2 values
all_r_squared, average_r_squared = Analyse.calculate_r_square(Input_data, Output_data)
print(average_r_squared)

In [ ]:
#Plot input vs output
#run through this to check it works with reset kernal!
data_analysis.plot_hexbin_log_frequency(Input_data[:,0], Output_data[:, 0] , xlabel='Input', ylabel='Output', title='') #change index to access different variable plots


## Test Trained Mode

In [ ]:
#import test data as numpy array 
Testing_data = np.loadtxt('testing_data2.csv',delimiter = ',')

## Preprocess Test data

In [ ]:
#seperate categorical and continuous

categorical_data_test = np.delete(Testing_data, 5, axis=1)
x6_test = Testing_data[:, 5]

In [ ]:
#Preprocess Categorical Data

#apply even spacing
mapped_test = preprocessor.map_unique_values_to_columns(categorical_data_test)


#order

ordered_test = preprocessor.order_by_frequency(mapped_test)

#normalise 
ordered_min_max_test = preprocessing.min_max(ordered_test)

In [ ]:
#Preprocess continuous data

log_x6_test = np.log10(x6_test)
x6_logged_normalized_test = preprocessing.min_max(log_x6_test)

In [ ]:
Input_data_test = np.column_stack((ordered_min_max_test, x6_logged_normalized_test))

## AutoEncoder on Test Data

In [ ]:
latent_space_representation_test = AutoEncoder.encoder.predict(Input_data_test)

Output_data_test = AutoEncoder.decoder.predict(latent_space_representation_test)

In [ ]:
Reconstruction_loss = np.mean(np.square(Input_data_test - Output_data_test), axis = 1)

In [ ]:
anomaly_truth = Reconstruction_loss > Threshold

anomaly_indices = np.where(anomaly_truth)[0]

anomalies = Input_data_test[anomaly_truth]

print("Anomalies:")
print(anomalies)

print("Indices of anomalies in Test_data:")
print(anomaly_indices)

print("Number of anomalies:", len(anomalies))

## Test Data Analysis

In [ ]:
Test_grad, Test_grad_average = Analyse.calculate_average_grad(Input_data_test, Output_data_test)
print(Test_grad_average)

In [ ]:
Test_R2, Test_R2_average = Analyse.calculate_r_square(Input_data_test, Output_data_test)
print(Test_R2_average)

## Compare to George IDs

In [ ]:
df = pd.read_csv('George_Anomalies.csv')
George_IDs = df['id']
array_of_values = np.array(George_IDs, dtype=int)

In [ ]:
# Calculate the intersection of the two arrays
intersection = np.intersect1d(George_IDs, anomaly_indices)

# Get the number of values shared
shared_count = len(intersection)

print("Number of shared values:", shared_count)